### ISSUE TITLE
Stuck juggling different forks

### ISSUE THREAD

**Issue by ash-burnt** [osmosis-labs/fee-abstraction#12]
We have an open PR attempting to integrate Fee Abstraction: https://github.com/burnt-labs/xion/pull/91

Currently, the situation is this. We need to point to the notional fork, since it is the only one supporting ibc-go v7. For some reason, that fork points at a Notional specific fork of Packet Forward Middleware. We don't intend to point at a non-standard fork of a common IBC module, so we have a replace directive in our go.mod pointing it back at ibc-apps. 

This causes an issues like so:
`go: github.com/cosmos/ibc-apps/middleware/packet-forward-middleware/v7@v7.0.0-20230802211043-d72e83c94350 used for two different module paths (github.com/cosmos/ibc-apps/middleware/packet-forward-middleware/v7 and github.com/strangelove-ventures/packet-forward-middleware/v7)
`

**Comment by GNaD13** [comment]
Hi @ash-burnt. Thanks for your feedback. We will fix it

**Comment by GNaD13** [comment]
Hi @ash-burnt, We have updated with the PFM. Your issue should be okay now.
https://github.com/notional-labs/fee-abstraction/tree/sdk47

**Comment by ash-burnt** [comment]
Yes, looks good to me
