### ISSUE TITLE
fee abstraction channel freeze easily after either a single failed ibc query or failed cross - chain swap

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [osmosis-labs/fee-abstraction#153]
* should never freeze a fee abstraction channel 
* should set OUTDATED state for a fee abstraction channel if unable to ibq query, or fail to cross - chain swap after 5 retries. If OUTDATED, chain should retry in the next 30 mins.

With current logic, once a connection is frozen, the chain will not perform IBC query to break that.

- [x] ibc query
- [x] cross - chain swap

states for a fee abstraction channel:
1. UPDATED
2. OUTDATED
3. FROZEN

**Comment by faddat** [comment]
Very interesting.  

I think this is surely an improvement.

Thanks!
