### ISSUE TITLE
Improve crosschain swap call

### ISSUE THREAD

**Issue by tnv1** [osmosis-labs/fee-abstraction#155]
In the current implementation, cross swap is called each end of epoch. It's ineffective when amount of token maybe very small.

Need add a field `MinSwapAmount` on each `HostZoneConfig`, cross swap should be called when bypass `MinSwapAmount` value.

**Comment by nghuyenthevinh2000** [comment]
can we improve this further to only make the swap when it is profitable to do such

**Comment by nghuyenthevinh2000** [comment]
> @nghuyenthevinh2000 - I'm not sure that would be an improvement. I think that we should continue to do it regularly even when the amount of token is small. Since this is critical infrastructure, I think that it is better to be routine.

this is debatable I suppose, I am most worried about fee abstraction module will cross - chain swap at potentially great loss if there is a price dump. More live running observation is in need.

**Comment by faddat** [comment]
It should do so no matter what.  Let's say once an hour or even more frequently. 

In this case it isn't likely to be affected by the scenario you mentioned here.
