### ISSUE TITLE
move from interchaintest to starship

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/fee-abstraction#158]
While neither of these is perfect, starship doesn't require a whole bunch of extra code in the repository.

I'm of the mind to even remove interchaintest from this repository, wdyt @nghuyenthevinh2000 ?

**Comment by nghuyenthevinh2000** [comment]
I can explore that, cosmology starship looks kubernetes enough to me :)))

**Comment by tropicaldog** [comment]
@faddat after playing around with starship I think it isn't ready to suitable interchaintest. Many issue related to IBC, which make it impossible to test feeabs.
