### ISSUE TITLE
Investigate speeding up interchaintest

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/fee-abstraction#60]
It might be possible to get interchaintest to run more quickly by pre-building some of the contents of the docker image.  Let's see if we can make that happen.

**Comment by GNaD13** [comment]
@anhductn2001 could you check this issue?

**Comment by anhductn2001** [comment]
OK, Let me check!

**Comment by faddat** [comment]
@anhductn2001 -- fyi, the issue seems to me to be that the "build and push" step takes unreasonably long.
