### ISSUE TITLE
Invalid version: unknown revision v0.34.26

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/fee-abstraction#8]
We are getting some reports of 

```
go: [github.com/tendermint/tendermint@v0.34.26](http://github.com/tendermint/tendermint@v0.34.26): invalid version: unknown revision v0.34.26
```

Used: 
https://github.com/search?q=repo%3Aosmosis-labs%2Ffee-abstraction%20v0.34.26&type=code

**Comment by ash-burnt** [comment]
Had to add `replace  github.com/tendermint/tendermint => github.com/informalsystems/tendermint v0.34.24
`
to get around this
