### ISSUE TITLE
Cannot use 'app.TransferKeeper'

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/fee-abstraction#9]
We have an integrator getting the following error message:

`Cannot use 'app.TransferKeeper' (type "[github.com/cosmos/ibc-go/v7/modules/apps/transfer/keeper](http://github.com/cosmos/ibc-go/v7/modules/apps/transfer/keeper)".Keeper) as the type "[github.com/cosmos/ibc-go/v4/modules/apps/transfer/keeper](http://github.com/cosmos/ibc-go/v4/modules/apps/transfer/keeper)".Keeper
`

```
app.FeeAbsKeeper = feeabskeeper.NewKeeper(
    appCodec,
    keys[feeabstypes.StoreKey],
    keys[feeabstypes.MemStoreKey],
    app.GetSubspace(feeabstypes.ModuleName),
    app.StakingKeeper,
    app.AccountKeeper,
    app.BankKeeper,
    app.TransferKeeper,
    app.IBCKeeper.ChannelKeeper,
    &app.IBCKeeper.PortKeeper,
    scopedFeeabsKeeper,
)...
```

is the `feeabskeeper` module  compatible with IBC v7?

**Comment by vuong177** [comment]
@daniel-farina now fee abs only supports IBC v4.

**Comment by vuong177** [comment]
We're working on support sdk47 && ibc v7 in this branch : https://github.com/osmosis-labs/fee-abstraction/tree/minh/sdk47

**Comment by daniel-farina** [comment]
Thank you for the context @vuong177. What's the current timeline for the support of sdk47?

**Comment by GNaD13** [comment]
Hi @daniel-farina we done with sdk47. Pls check this branch https://github.com/notional-labs/fee-abstraction/tree/sdk47

**Comment by ash-burnt** [comment]
Looks good using the sdk47 version of notional

**Comment by vuong177** [comment]
problem solve by sdk47 version
